apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: nautobot-default
    app.kubernetes.io/instance: nautobot
    app.kubernetes.io/name: nautobot
  name: nautobot-default
  namespace: example
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: nautobot-default
    app.kubernetes.io/instance: nautobot
    app.kubernetes.io/name: nautobot
  sessionAffinity: None
  type: ClusterIP
